# Generated by Django 4.2.20 on 2025-04-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=150)),
                ("department", models.CharField(max_length=100)),
                ("course_num", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("credits", models.IntegerField()),
                (
                    "prerequisite",
                    models.ForeignKey(
                        blank=True,
                        db_column="prerequisite",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="course_management_sys.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "section_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("semester", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("schedule", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_management_sys.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "instructor_id",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("start_date", models.DateField()),
                ("program", models.CharField(max_length=100)),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "enrollment_id",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=50)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("enrollment_date", models.DateField()),
                (
                    "course_section",
                    models.ForeignKey(
                        db_column="section_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_management_sys.coursesection",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_management_sys.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coursesection",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_management_sys.instructor",
            ),
        ),
    ]
